# MIT License

# Copyright (c) 2021 BamPeers

# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

on:
  pull_request:
  push:
    branches:
      - main
      - "*ci*"
    paths:
      - folder1/**

name: Check and Lint for embedded

defaults:
  run:
    working-directory: embedded_rtic

jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo_check
        run: |
          rustup toolchain install nightly-2024-04-07 --force
          rustup target add thumbv7em-none-eabihf
          cargo +nightly clippy
  check:
    needs: [clippy]
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo_check
        run: |
          rustup toolchain install nightly-2024-04-07 --force
          rustup target add thumbv7em-none-eabihf
          cargo +nightly check

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: fmt check
        run: |
          rustup toolchain install nightly-2024-04-07 --force
          rustup component add rustfmt
          cargo fmt --all -- --check

  build:
    needs: [check, clippy]
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: cargo_check
        run: |
          rustup toolchain install nightly-2024-04-07 --force
          rustup target add thumbv7em-none-eabihf
          ls -la
          cargo +nightly build --release
